export interface GameEntry {
  title: string;
  url: string;
  category: string;
  emoji: string;
}

export const CATEGORIES = [
  "All",
  "IO Games",
  "Arcade",
  "Puzzle",
  "Sports",
  "Action",
  "Strategy",
  "Classics",
  "Platformer",
  "Portals",
];

export const GAMES: GameEntry[] = [
  // ─── IO GAMES ───────────────────────────────────────────────────────────────
  {
    title: "Slither.io",
    url: "https://slither.io",
    category: "IO Games",
    emoji: "🐍",
  },
  {
    title: "Agar.io",
    url: "https://agar.io",
    category: "IO Games",
    emoji: "🟢",
  },
  {
    title: "Diep.io",
    url: "https://diep.io",
    category: "IO Games",
    emoji: "🔫",
  },
  {
    title: "Krunker.io",
    url: "https://krunker.io",
    category: "IO Games",
    emoji: "🎯",
  },
  {
    title: "Shell Shockers",
    url: "https://shellshock.io",
    category: "IO Games",
    emoji: "🥚",
  },
  {
    title: "ZombsRoyale.io",
    url: "https://zombsroyale.io",
    category: "IO Games",
    emoji: "🧟",
  },
  {
    title: "Starblast.io",
    url: "https://starblast.io",
    category: "IO Games",
    emoji: "🚀",
  },
  {
    title: "Paper.io 2",
    url: "https://paper-io.com",
    category: "IO Games",
    emoji: "📄",
  },
  {
    title: "Mope.io",
    url: "https://mope.io",
    category: "IO Games",
    emoji: "🐾",
  },
  {
    title: "Wormate.io",
    url: "https://wormate.io",
    category: "IO Games",
    emoji: "🐛",
  },
  {
    title: "Lordz.io",
    url: "https://lordz.io",
    category: "IO Games",
    emoji: "⚔️",
  },
  {
    title: "Stabfish2.io",
    url: "https://stabfish2.io",
    category: "IO Games",
    emoji: "🐟",
  },
  {
    title: "Defly.io",
    url: "https://defly.io",
    category: "IO Games",
    emoji: "✈️",
  },
  {
    title: "Splix.io",
    url: "https://splix.io",
    category: "IO Games",
    emoji: "🟦",
  },
  {
    title: "Powerline.io",
    url: "https://powerline.io",
    category: "IO Games",
    emoji: "⚡",
  },
  {
    title: "Superhex.io",
    url: "https://superhex.io",
    category: "IO Games",
    emoji: "🔷",
  },
  {
    title: "Hexar.io",
    url: "https://hexar.io",
    category: "IO Games",
    emoji: "🔹",
  },
  {
    title: "Gota.io",
    url: "https://gota.io",
    category: "IO Games",
    emoji: "💧",
  },
  {
    title: "1v1.LOL",
    url: "https://1v1.lol",
    category: "IO Games",
    emoji: "🏗️",
  },
  {
    title: "Venge.io",
    url: "https://venge.io",
    category: "IO Games",
    emoji: "💀",
  },
  {
    title: "Vertix.io",
    url: "https://vertix.io",
    category: "IO Games",
    emoji: "🌀",
  },
  {
    title: "Skribbl.io",
    url: "https://skribbl.io",
    category: "IO Games",
    emoji: "✏️",
  },
  {
    title: "Gartic.io",
    url: "https://gartic.io",
    category: "IO Games",
    emoji: "🎨",
  },
  {
    title: "Drawasaurus",
    url: "https://www.drawasaurus.org",
    category: "IO Games",
    emoji: "🦕",
  },
  {
    title: "Sketchful.io",
    url: "https://sketchful.io",
    category: "IO Games",
    emoji: "🖌️",
  },
  {
    title: "Flyordie.io",
    url: "https://flyordie.io",
    category: "IO Games",
    emoji: "🦋",
  },
  {
    title: "Warbot.io",
    url: "https://warbot.io",
    category: "IO Games",
    emoji: "🤖",
  },
  {
    title: "Spinz.io",
    url: "https://spinz.io",
    category: "IO Games",
    emoji: "🌪️",
  },
  {
    title: "Pigs.gg",
    url: "https://pigs.gg",
    category: "IO Games",
    emoji: "🐷",
  },
  {
    title: "Gulper.io",
    url: "https://gulper.io",
    category: "IO Games",
    emoji: "🐊",
  },
  {
    title: "Foes.io",
    url: "https://foes.io",
    category: "IO Games",
    emoji: "🗡️",
  },
  {
    title: "Brutes.io",
    url: "https://brutes.io",
    category: "IO Games",
    emoji: "💪",
  },
  {
    title: "Narwhale.io",
    url: "https://narwhale.io",
    category: "IO Games",
    emoji: "🦄",
  },
  {
    title: "Wings.io",
    url: "https://wings.io",
    category: "IO Games",
    emoji: "🛩️",
  },
  {
    title: "Hole.io",
    url: "https://hole-io.com",
    category: "IO Games",
    emoji: "🕳️",
  },
  {
    title: "Bonk.io",
    url: "https://bonk.io",
    category: "IO Games",
    emoji: "🏀",
  },
  {
    title: "Snowball.io",
    url: "https://snowball.io",
    category: "IO Games",
    emoji: "❄️",
  },
  {
    title: "Braains.io",
    url: "https://braains.io",
    category: "IO Games",
    emoji: "🧠",
  },
  {
    title: "Wilds.io",
    url: "https://wilds.io",
    category: "IO Games",
    emoji: "🐺",
  },
  {
    title: "MiniRoyale.io",
    url: "https://miniroyale.io",
    category: "IO Games",
    emoji: "🏆",
  },
  {
    title: "BuildRoyale.io",
    url: "https://buildroyale.io",
    category: "IO Games",
    emoji: "🏰",
  },
  {
    title: "SmashKarts.io",
    url: "https://smashkarts.io",
    category: "IO Games",
    emoji: "🚗",
  },
  { title: "Ev.io", url: "https://ev.io", category: "IO Games", emoji: "👾" },
  {
    title: "Oceanar.io",
    url: "https://oceanar.io",
    category: "IO Games",
    emoji: "🌊",
  },
  {
    title: "Worm.is",
    url: "https://worm.is",
    category: "IO Games",
    emoji: "🐍",
  },
  {
    title: "IO Games Space",
    url: "https://iogames.space",
    category: "IO Games",
    emoji: "🌐",
  },
  {
    title: "Dodgeball.io",
    url: "https://dodgeball.io",
    category: "IO Games",
    emoji: "⚽",
  },
  {
    title: "Chompers.io",
    url: "https://chompers.io",
    category: "IO Games",
    emoji: "😬",
  },
  {
    title: "Zapper.io",
    url: "https://zapper.io",
    category: "IO Games",
    emoji: "⚡",
  },
  {
    title: "Nend.io",
    url: "https://nend.io",
    category: "IO Games",
    emoji: "🎮",
  },
  {
    title: "Gotd.io",
    url: "https://gotd.io",
    category: "IO Games",
    emoji: "🎯",
  },
  {
    title: "Bubbles.io",
    url: "https://bubbles.io",
    category: "IO Games",
    emoji: "🫧",
  },
  {
    title: "Lordz2.io",
    url: "https://lordz2.io",
    category: "IO Games",
    emoji: "🏯",
  },
  {
    title: "Yohoho.io",
    url: "https://yohoho.io",
    category: "IO Games",
    emoji: "🏴‍☠️",
  },
  {
    title: "Brawlhalla",
    url: "https://www.brawlhalla.com",
    category: "IO Games",
    emoji: "🥊",
  },
  {
    title: "Tribals.io",
    url: "https://tribals.io",
    category: "IO Games",
    emoji: "🗿",
  },
  {
    title: "Zlap.io",
    url: "https://zlap.io",
    category: "IO Games",
    emoji: "🔨",
  },
  {
    title: "Rocket Bot Royale",
    url: "https://rocketbotroyale.winterpixel.io",
    category: "IO Games",
    emoji: "🚀",
  },
  {
    title: "Lagged IO Games",
    url: "https://lagged.com/en/g/io",
    category: "IO Games",
    emoji: "🕹️",
  },

  // ─── ARCADE ─────────────────────────────────────────────────────────────────
  { title: "Poki", url: "https://poki.com", category: "Portals", emoji: "🎮" },
  {
    title: "CrazyGames",
    url: "https://www.crazygames.com",
    category: "Portals",
    emoji: "🃏",
  },
  {
    title: "Y8 Games",
    url: "https://www.y8.com",
    category: "Portals",
    emoji: "🎲",
  },
  { title: "Friv", url: "https://friv.com", category: "Portals", emoji: "🌈" },
  { title: "Kizi", url: "https://kizi.com", category: "Portals", emoji: "🦊" },
  {
    title: "Silvergames",
    url: "https://www.silvergames.com",
    category: "Portals",
    emoji: "🥈",
  },
  {
    title: "AddictingGames",
    url: "https://www.addictinggames.com",
    category: "Portals",
    emoji: "🕹️",
  },
  {
    title: "Miniclip",
    url: "https://www.miniclip.com",
    category: "Portals",
    emoji: "🎯",
  },
  {
    title: "GameSnacks",
    url: "https://gamesnacks.com",
    category: "Portals",
    emoji: "🍿",
  },
  {
    title: "HTML5 Games",
    url: "https://html5games.com",
    category: "Portals",
    emoji: "5️⃣",
  },
  {
    title: "itch.io",
    url: "https://itch.io",
    category: "Portals",
    emoji: "🌸",
  },
  {
    title: "Newgrounds",
    url: "https://www.newgrounds.com",
    category: "Portals",
    emoji: "🅽",
  },
  {
    title: "Kongregate",
    url: "https://www.kongregate.com",
    category: "Portals",
    emoji: "🦍",
  },
  {
    title: "Armor Games",
    url: "https://armorgames.com",
    category: "Portals",
    emoji: "🛡️",
  },
  {
    title: "Nitrome",
    url: "https://www.nitrome.com",
    category: "Portals",
    emoji: "🧪",
  },
  {
    title: "Cool Math Games",
    url: "https://www.coolmathgames.com",
    category: "Portals",
    emoji: "🧮",
  },
  {
    title: "ABCya",
    url: "https://www.abcya.com",
    category: "Portals",
    emoji: "🔤",
  },
  {
    title: "Funbrain",
    url: "https://www.funbrain.com",
    category: "Portals",
    emoji: "🧠",
  },
  {
    title: "Hooda Math",
    url: "https://www.hoodamath.com",
    category: "Portals",
    emoji: "➗",
  },
  {
    title: "Primary Games",
    url: "https://www.primarygames.com",
    category: "Portals",
    emoji: "🎒",
  },
  {
    title: "Math Playground",
    url: "https://www.mathplayground.com",
    category: "Portals",
    emoji: "📐",
  },
  {
    title: "Agame",
    url: "https://www.agame.com",
    category: "Portals",
    emoji: "🎮",
  },
  {
    title: "Two Player Games",
    url: "https://www.twoplayergames.org",
    category: "Portals",
    emoji: "👥",
  },
  {
    title: "Unblocked Games",
    url: "https://unblockedgames.world",
    category: "Portals",
    emoji: "🔓",
  },
  {
    title: "Games Unblocked",
    url: "https://gamesunblocked.org",
    category: "Portals",
    emoji: "🔓",
  },
  {
    title: "Scratch",
    url: "https://scratch.mit.edu/explore/projects/games",
    category: "Portals",
    emoji: "🐱",
  },

  // ─── ARCADE (individual) ────────────────────────────────────────────────────
  {
    title: "Google Snake",
    url: "https://www.google.com/logos/fnbx/snake_arcade/v17/canvas_app.html",
    category: "Arcade",
    emoji: "🐍",
  },
  {
    title: "Snake.io",
    url: "https://snake.io",
    category: "Arcade",
    emoji: "🐍",
  },
  {
    title: "Pac-Man Live",
    url: "https://pacman.live",
    category: "Arcade",
    emoji: "👻",
  },
  {
    title: "Free Tetris",
    url: "https://freetetris.org",
    category: "Arcade",
    emoji: "🟦",
  },
  {
    title: "Jstris (Tetris)",
    url: "https://jstris.jezevec10.com",
    category: "Arcade",
    emoji: "🟨",
  },
  {
    title: "Tetris.com",
    url: "https://tetris.com/play-tetris",
    category: "Arcade",
    emoji: "🟥",
  },
  { title: "2048", url: "https://2048.la", category: "Puzzle", emoji: "🔢" },
  {
    title: "2048 Original",
    url: "https://gabrielecirulli.github.io/2048",
    category: "Puzzle",
    emoji: "2️⃣",
  },
  {
    title: "1024 Puzzle",
    url: "https://www.crazygames.com/game/1024",
    category: "Puzzle",
    emoji: "🔢",
  },
  {
    title: "Geometry Dash",
    url: "https://geometrydash.io",
    category: "Arcade",
    emoji: "⬛",
  },
  {
    title: "Moto X3M",
    url: "https://www.crazygames.com/game/moto-x3m",
    category: "Arcade",
    emoji: "🏍️",
  },
  {
    title: "Slope",
    url: "https://slope-game.com",
    category: "Arcade",
    emoji: "⬇️",
  },
  {
    title: "Run 3",
    url: "https://www.coolmathgames.com/0-run-3",
    category: "Arcade",
    emoji: "🏃",
  },
  {
    title: "Flappy Bird",
    url: "https://flappybird.io",
    category: "Arcade",
    emoji: "🐦",
  },
  {
    title: "Dino Game",
    url: "https://chromedino.com",
    category: "Arcade",
    emoji: "🦕",
  },
  {
    title: "Stick Hero",
    url: "https://www.crazygames.com/game/stick-hero",
    category: "Arcade",
    emoji: "🦷",
  },
  {
    title: "Space Invaders",
    url: "https://spaceinvaders.codeplex.com",
    category: "Arcade",
    emoji: "👾",
  },
  {
    title: "Asteroids",
    url: "https://www.masswerk.at/spacewar/asteroids.html",
    category: "Classics",
    emoji: "🪨",
  },
  {
    title: "Breakout",
    url: "https://www.crazygames.com/game/breakout",
    category: "Arcade",
    emoji: "🧱",
  },
  {
    title: "Fruit Ninja",
    url: "https://www.crazygames.com/game/fruit-ninja",
    category: "Arcade",
    emoji: "🍉",
  },
  {
    title: "Angry Birds Online",
    url: "https://www.crazygames.com/game/angry-birds-reloaded",
    category: "Arcade",
    emoji: "🐦",
  },
  {
    title: "Minecraft Classic",
    url: "https://classic.minecraft.net",
    category: "Arcade",
    emoji: "⛏️",
  },
  {
    title: "Little Alchemy",
    url: "https://littlealchemy2.com",
    category: "Puzzle",
    emoji: "⚗️",
  },
  {
    title: "Cut the Rope",
    url: "https://www.crazygames.com/game/cut-the-rope-remastered",
    category: "Puzzle",
    emoji: "🍭",
  },
  {
    title: "Parking Fury",
    url: "https://www.crazygames.com/game/parking-fury-3d",
    category: "Arcade",
    emoji: "🅿️",
  },
  {
    title: "Tank Battle",
    url: "https://www.crazygames.com/game/tank-battle",
    category: "Action",
    emoji: "🪖",
  },
  {
    title: "Stickman Hook",
    url: "https://www.crazygames.com/game/stickman-hook",
    category: "Arcade",
    emoji: "🕷️",
  },
  {
    title: "Happy Wheels",
    url: "https://www.totaljerkface.com/happy_wheels.tjf",
    category: "Arcade",
    emoji: "🚴",
  },
  {
    title: "Drift Hunters",
    url: "https://drifthunters.io",
    category: "Arcade",
    emoji: "🚗",
  },
  {
    title: "Hills of Steel",
    url: "https://www.crazygames.com/game/hills-of-steel",
    category: "Action",
    emoji: "⛰️",
  },
  {
    title: "Doodle Jump",
    url: "https://doodlejump.io",
    category: "Arcade",
    emoji: "🟢",
  },
  {
    title: "Bubble Shooter",
    url: "https://www.crazygames.com/game/bubble-shooter",
    category: "Arcade",
    emoji: "🫧",
  },
  {
    title: "Candy Crush Saga",
    url: "https://king.com/game/candycrush",
    category: "Puzzle",
    emoji: "🍬",
  },
  {
    title: "Plants vs Zombies",
    url: "https://www.crazygames.com/game/plants-vs-zombies",
    category: "Strategy",
    emoji: "🌻",
  },
  {
    title: "Tower Defense",
    url: "https://www.crazygames.com/game/tower-defense-king",
    category: "Strategy",
    emoji: "🗼",
  },
  {
    title: "Bloons TD",
    url: "https://ninjakiwi.com/Games/Tower-Defense/Bloons-TD-5.html",
    category: "Strategy",
    emoji: "🎈",
  },

  // ─── PUZZLE ─────────────────────────────────────────────────────────────────
  {
    title: "Wordle",
    url: "https://www.nytimes.com/games/wordle",
    category: "Puzzle",
    emoji: "🟩",
  },
  {
    title: "Wordplay",
    url: "https://wordplay.com",
    category: "Puzzle",
    emoji: "📝",
  },
  {
    title: "Jigsaw Planet",
    url: "https://www.jigsawplanet.com",
    category: "Puzzle",
    emoji: "🧩",
  },
  {
    title: "Crossword",
    url: "https://crossword.com",
    category: "Puzzle",
    emoji: "✏️",
  },
  {
    title: "NYT Games",
    url: "https://www.nytimes.com/games",
    category: "Puzzle",
    emoji: "🗞️",
  },
  {
    title: "Sudoku.com",
    url: "https://sudoku.com",
    category: "Puzzle",
    emoji: "🔢",
  },
  {
    title: "Web Sudoku",
    url: "https://www.websudoku.com",
    category: "Puzzle",
    emoji: "9️⃣",
  },
  {
    title: "Kakuro",
    url: "https://www.kakuro.com",
    category: "Puzzle",
    emoji: "➕",
  },
  {
    title: "Nonograms",
    url: "https://www.nonograms.org",
    category: "Puzzle",
    emoji: "🔲",
  },
  {
    title: "Simon",
    url: "https://www.crazygames.com/game/simon-says",
    category: "Puzzle",
    emoji: "🟡",
  },
  {
    title: "Minesweeper",
    url: "https://minesweeper.online",
    category: "Puzzle",
    emoji: "💣",
  },
  {
    title: "Mahjong",
    url: "https://www.mahjong.co.uk",
    category: "Classics",
    emoji: "🀄",
  },
  {
    title: "Mahjongg",
    url: "https://mahjongg.com",
    category: "Classics",
    emoji: "🀄",
  },
  {
    title: "Solitaire",
    url: "https://solitaire.com",
    category: "Classics",
    emoji: "🃏",
  },
  {
    title: "FreeCell",
    url: "https://freecell.com",
    category: "Classics",
    emoji: "🃏",
  },
  {
    title: "Spider Solitaire",
    url: "https://spidersolitaire.com",
    category: "Classics",
    emoji: "🕷️",
  },
  {
    title: "Word Search",
    url: "https://wordsearch.net",
    category: "Puzzle",
    emoji: "🔍",
  },
  {
    title: "Anagram",
    url: "https://www.crazygames.com/game/anagram-scramble",
    category: "Puzzle",
    emoji: "🔤",
  },
  {
    title: "4 Pics 1 Word",
    url: "https://www.crazygames.com/game/4-pics-1-word-online",
    category: "Puzzle",
    emoji: "🖼️",
  },
  {
    title: "Flow Free",
    url: "https://www.crazygames.com/game/pipe-mania",
    category: "Puzzle",
    emoji: "🌊",
  },
  {
    title: "Quordle",
    url: "https://www.merriam-webster.com/games/quordle",
    category: "Puzzle",
    emoji: "📚",
  },
  {
    title: "Connections",
    url: "https://www.nytimes.com/games/connections",
    category: "Puzzle",
    emoji: "🔗",
  },
  {
    title: "Spelling Bee",
    url: "https://www.nytimes.com/puzzles/spelling-bee",
    category: "Puzzle",
    emoji: "🐝",
  },
  {
    title: "Mini Crossword",
    url: "https://www.nytimes.com/crosswords/game/mini",
    category: "Puzzle",
    emoji: "🔲",
  },
  {
    title: "Boggle",
    url: "https://www.crazygames.com/game/boggle",
    category: "Puzzle",
    emoji: "📝",
  },

  // ─── STRATEGY ───────────────────────────────────────────────────────────────
  {
    title: "Chess.com",
    url: "https://www.chess.com/play/computer",
    category: "Strategy",
    emoji: "♟️",
  },
  {
    title: "Lichess",
    url: "https://lichess.org",
    category: "Strategy",
    emoji: "♟️",
  },
  {
    title: "Checkers Online",
    url: "https://www.checkers.online",
    category: "Strategy",
    emoji: "⚫",
  },
  {
    title: "Backgammon",
    url: "https://www.backgammon.de",
    category: "Strategy",
    emoji: "🎲",
  },
  {
    title: "Go",
    url: "https://online-go.com",
    category: "Strategy",
    emoji: "⭕",
  },
  {
    title: "Risk",
    url: "https://www.crazygames.com/game/warzone",
    category: "Strategy",
    emoji: "🗺️",
  },
  {
    title: "Catan Universe",
    url: "https://colonist.io",
    category: "Strategy",
    emoji: "🏝️",
  },
  {
    title: "Dominoes",
    url: "https://www.dominoes.com",
    category: "Strategy",
    emoji: "🁢",
  },
  {
    title: "Connect Four",
    url: "https://www.crazygames.com/game/connect-four",
    category: "Strategy",
    emoji: "🔴",
  },
  {
    title: "Battleship",
    url: "https://www.battleship-game.org",
    category: "Strategy",
    emoji: "⚓",
  },
  {
    title: "Tic Tac Toe",
    url: "https://www.crazygames.com/game/tic-tac-toe",
    category: "Strategy",
    emoji: "❌",
  },
  {
    title: "Stratego",
    url: "https://www.stratego.com",
    category: "Strategy",
    emoji: "🏴",
  },
  {
    title: "Age of War",
    url: "https://www.crazygames.com/game/age-of-war",
    category: "Strategy",
    emoji: "⚔️",
  },
  {
    title: "Clash of Clans Online",
    url: "https://www.crazygames.com/game/clash-of-clans-online",
    category: "Strategy",
    emoji: "🏰",
  },
  {
    title: "Stick War",
    url: "https://www.crazygames.com/game/stick-war",
    category: "Strategy",
    emoji: "🗡️",
  },
  {
    title: "Kingdom Rush",
    url: "https://armorgames.com/play/15285/kingdom-rush",
    category: "Strategy",
    emoji: "👑",
  },
  {
    title: "GeoGuessr",
    url: "https://www.geoguessr.com",
    category: "Strategy",
    emoji: "🌍",
  },
  {
    title: "Worldle",
    url: "https://worldle.teuteuf.fr",
    category: "Strategy",
    emoji: "🌐",
  },
  {
    title: "Ludo Online",
    url: "https://www.ludo.club",
    category: "Strategy",
    emoji: "🎲",
  },
  {
    title: "8 Ball Pool",
    url: "https://www.miniclip.com/games/8-ball-pool-multiplayer",
    category: "Strategy",
    emoji: "🎱",
  },

  // ─── ACTION ─────────────────────────────────────────────────────────────────
  {
    title: "Poxel.io",
    url: "https://poxel.io",
    category: "Action",
    emoji: "🎮",
  },
  { title: "2v2.io", url: "https://2v2.io", category: "Action", emoji: "⚔️" },
  {
    title: "Fall Zone",
    url: "https://fallzone.io",
    category: "Action",
    emoji: "🏋️",
  },
  {
    title: "Bloxd.io",
    url: "https://bloxd.io",
    category: "Action",
    emoji: "🟫",
  },
  {
    title: "Bullet Force",
    url: "https://www.crazygames.com/game/bullet-force-multiplayer",
    category: "Action",
    emoji: "💥",
  },
  {
    title: "Combat Reloaded",
    url: "https://www.crazygames.com/game/combat-reloaded",
    category: "Action",
    emoji: "🔫",
  },
  {
    title: "Crossfire",
    url: "https://www.crazygames.com/game/crossfire",
    category: "Action",
    emoji: "🔥",
  },
  {
    title: "Warmerise",
    url: "https://warmerise.com",
    category: "Action",
    emoji: "💀",
  },
  {
    title: "Superhot WebGL",
    url: "https://superhotgame.com/play-superhot-web",
    category: "Action",
    emoji: "🕶️",
  },
  {
    title: "Pixel Warfare",
    url: "https://www.crazygames.com/game/pixel-warfare-5",
    category: "Action",
    emoji: "🔲",
  },
  {
    title: "Mad GunZ",
    url: "https://madgunz.io",
    category: "Action",
    emoji: "🔫",
  },
  {
    title: "Ninja.io",
    url: "https://ninja.io",
    category: "Action",
    emoji: "🥷",
  },
  {
    title: "Betrayal.io",
    url: "https://betrayal.io",
    category: "Action",
    emoji: "🗡️",
  },
  {
    title: "Deadshot.io",
    url: "https://deadshot.io",
    category: "Action",
    emoji: "🎯",
  },
  {
    title: "Rooftop Snipers",
    url: "https://www.crazygames.com/game/rooftop-snipers",
    category: "Action",
    emoji: "🏙️",
  },
  {
    title: "Getaway Shootout",
    url: "https://www.newgrounds.com/portal/view/770153",
    category: "Action",
    emoji: "🚗",
  },
  {
    title: "Boxhead Zombies",
    url: "https://www.crazygames.com/game/boxhead-2play-rooms",
    category: "Action",
    emoji: "🟫",
  },
  {
    title: "Zombotron",
    url: "https://www.crazygames.com/game/zombotron",
    category: "Action",
    emoji: "🧟",
  },
  {
    title: "Hanger 2",
    url: "https://www.crazygames.com/game/hanger-2",
    category: "Action",
    emoji: "🕷️",
  },
  {
    title: "Superfighters",
    url: "https://www.crazygames.com/game/superfighters",
    category: "Action",
    emoji: "🥊",
  },

  // ─── PLATFORMER / ADVENTURE ─────────────────────────────────────────────────
  {
    title: "Fireboy & Watergirl",
    url: "https://www.crazygames.com/game/fireboy-and-watergirl-forest-temple",
    category: "Platformer",
    emoji: "🔥",
  },
  {
    title: "Getting Over It",
    url: "https://www.crazygames.com/game/getting-over-it",
    category: "Platformer",
    emoji: "⛏️",
  },
  {
    title: "Temple Run 2",
    url: "https://www.crazygames.com/game/temple-run-2",
    category: "Platformer",
    emoji: "🏛️",
  },
  {
    title: "Subway Surfers",
    url: "https://www.crazygames.com/game/subway-surfers",
    category: "Platformer",
    emoji: "🛹",
  },
  {
    title: "Geometry Dash CG",
    url: "https://www.crazygames.com/game/geometry-dash",
    category: "Platformer",
    emoji: "⬛",
  },
  {
    title: "Super Mario Flash",
    url: "https://supermarioflash.net",
    category: "Platformer",
    emoji: "🍄",
  },
  {
    title: "Sonic the Hedgehog",
    url: "https://www.crazygames.com/game/sonic-the-hedgehog",
    category: "Platformer",
    emoji: "🔵",
  },
  {
    title: "N-Game",
    url: "https://www.thewayoftheninja.org/n_times.html",
    category: "Platformer",
    emoji: "🥷",
  },
  {
    title: "Fancy Pants",
    url: "https://www.crazygames.com/game/fancy-pants-adventure",
    category: "Platformer",
    emoji: "👖",
  },
  {
    title: "Papa's Games",
    url: "https://www.crazygames.com/game/papas-pizzeria",
    category: "Arcade",
    emoji: "🍕",
  },
  {
    title: "Electric Man 2",
    url: "https://www.crazygames.com/game/electric-man-2",
    category: "Platformer",
    emoji: "⚡",
  },
  {
    title: "Stickman Boost",
    url: "https://www.crazygames.com/game/stickman-boost",
    category: "Platformer",
    emoji: "🏃",
  },
  {
    title: "Vex 5",
    url: "https://www.crazygames.com/game/vex-5",
    category: "Platformer",
    emoji: "💀",
  },
  {
    title: "Short Life",
    url: "https://www.crazygames.com/game/short-life",
    category: "Platformer",
    emoji: "😅",
  },
  {
    title: "Google Chrome Dinosaur",
    url: "https://chromedino.com",
    category: "Arcade",
    emoji: "🦕",
  },

  // ─── SPORTS ─────────────────────────────────────────────────────────────────
  {
    title: "Football Games",
    url: "https://www.footballgames.us",
    category: "Sports",
    emoji: "🏈",
  },
  {
    title: "Basketball Games",
    url: "https://www.crazygames.com/game/basketball-stars",
    category: "Sports",
    emoji: "🏀",
  },
  {
    title: "Soccer Physics",
    url: "https://www.crazygames.com/game/soccer-physics-mobile",
    category: "Sports",
    emoji: "⚽",
  },
  {
    title: "Head Soccer",
    url: "https://www.crazygames.com/game/head-soccer",
    category: "Sports",
    emoji: "🏃",
  },
  {
    title: "Tennis Online",
    url: "https://www.crazygames.com/game/tennis",
    category: "Sports",
    emoji: "🎾",
  },
  {
    title: "8 Ball Pool",
    url: "https://www.crazygames.com/game/8-ball-billiards-classic",
    category: "Sports",
    emoji: "🎱",
  },
  {
    title: "Bowling",
    url: "https://www.crazygames.com/game/bowling-stars",
    category: "Sports",
    emoji: "🎳",
  },
  {
    title: "Mini Golf",
    url: "https://www.crazygames.com/game/mini-golf-friends",
    category: "Sports",
    emoji: "⛳",
  },
  {
    title: "Baseball Online",
    url: "https://www.crazygames.com/game/baseball-legend",
    category: "Sports",
    emoji: "⚾",
  },
  {
    title: "Ice Hockey",
    url: "https://www.crazygames.com/game/ice-hockey-league",
    category: "Sports",
    emoji: "🏒",
  },
  {
    title: "Boxing Live",
    url: "https://www.crazygames.com/game/boxing-live",
    category: "Sports",
    emoji: "🥊",
  },
  {
    title: "Racing Games",
    url: "https://www.crazygames.com/game/madalin-stunt-cars-2",
    category: "Sports",
    emoji: "🏎️",
  },
  {
    title: "Bike Racing",
    url: "https://www.crazygames.com/game/bike-racing",
    category: "Sports",
    emoji: "🚵",
  },
  {
    title: "Rocket League Online",
    url: "https://www.crazygames.com/game/rocket-league-online",
    category: "Sports",
    emoji: "🚀",
  },
  {
    title: "Football.io",
    url: "https://football.io",
    category: "Sports",
    emoji: "🏟️",
  },
  {
    title: "Penalty Shooters",
    url: "https://www.crazygames.com/game/penalty-shooters-2",
    category: "Sports",
    emoji: "⚽",
  },
  {
    title: "Slam Dunk",
    url: "https://www.crazygames.com/game/slam-dunk",
    category: "Sports",
    emoji: "🏀",
  },
  {
    title: "Golf Battle",
    url: "https://www.crazygames.com/game/golf-battle",
    category: "Sports",
    emoji: "⛳",
  },
  {
    title: "Skater XL Online",
    url: "https://www.crazygames.com/game/skate",
    category: "Sports",
    emoji: "🛹",
  },
  {
    title: "Stickman Tennis",
    url: "https://www.crazygames.com/game/stickman-tennis",
    category: "Sports",
    emoji: "🎾",
  },

  // ─── CLASSICS ───────────────────────────────────────────────────────────────
  {
    title: "Pac-Man",
    url: "https://pacman.live",
    category: "Classics",
    emoji: "👻",
  },
  {
    title: "Space Invaders",
    url: "https://www.crazygames.com/game/space-invaders",
    category: "Classics",
    emoji: "👾",
  },
  {
    title: "Tetris Classic",
    url: "https://tetris.com/play-tetris",
    category: "Classics",
    emoji: "🟦",
  },
  {
    title: "Pong",
    url: "https://www.crazygames.com/game/pong",
    category: "Classics",
    emoji: "🏓",
  },
  {
    title: "Atari Breakout",
    url: "https://www.crazygames.com/game/atari-breakout",
    category: "Classics",
    emoji: "🧱",
  },
  {
    title: "Donkey Kong",
    url: "https://www.crazygames.com/game/donkey-kong-classic",
    category: "Classics",
    emoji: "🦍",
  },
  {
    title: "Galaga",
    url: "https://www.crazygames.com/game/galaga",
    category: "Classics",
    emoji: "🛸",
  },
  {
    title: "Frogger",
    url: "https://www.crazygames.com/game/frogger",
    category: "Classics",
    emoji: "🐸",
  },
  {
    title: "Q*bert",
    url: "https://www.crazygames.com/game/qbert",
    category: "Classics",
    emoji: "🎮",
  },
  {
    title: "Centipede",
    url: "https://www.crazygames.com/game/centipede",
    category: "Classics",
    emoji: "🐛",
  },
  {
    title: "Joust",
    url: "https://www.crazygames.com/game/joust",
    category: "Classics",
    emoji: "🏇",
  },
  {
    title: "Missile Command",
    url: "https://www.crazygames.com/game/missile-command",
    category: "Classics",
    emoji: "🚀",
  },
  {
    title: "Dig Dug",
    url: "https://www.crazygames.com/game/dig-dug",
    category: "Classics",
    emoji: "⛏️",
  },
  {
    title: "Burger Time",
    url: "https://www.crazygames.com/game/burgertime",
    category: "Classics",
    emoji: "🍔",
  },
  {
    title: "Minesweeper Classic",
    url: "https://minesweeper.online",
    category: "Classics",
    emoji: "💣",
  },

  // ─── GEOGRAPHY/MISC ─────────────────────────────────────────────────────────
  {
    title: "Gimme the Air Pods",
    url: "https://geography-lesson-11.us",
    category: "Arcade",
    emoji: "🎧",
  },
  {
    title: "GeoGuessr",
    url: "https://www.geoguessr.com",
    category: "Strategy",
    emoji: "🌍",
  },
  {
    title: "Seterra Geography",
    url: "https://www.seterra.com",
    category: "Puzzle",
    emoji: "🗺️",
  },
  {
    title: "Maps Mania",
    url: "https://googlemapsmania.blogspot.com",
    category: "Puzzle",
    emoji: "🧭",
  },
  {
    title: "Sporcle",
    url: "https://www.sporcle.com/games/category/geography",
    category: "Puzzle",
    emoji: "🌐",
  },
];
