/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Message = IDL.Record({ 'content' : IDL.Text, 'role' : IDL.Text });

export const idlService = IDL.Service({
  'addMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'clearHistory' : IDL.Func([IDL.Text], [], []),
  'getHistory' : IDL.Func([IDL.Text], [IDL.Vec(Message)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Message = IDL.Record({ 'content' : IDL.Text, 'role' : IDL.Text });
  
  return IDL.Service({
    'addMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'clearHistory' : IDL.Func([IDL.Text], [], []),
    'getHistory' : IDL.Func([IDL.Text], [IDL.Vec(Message)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };